In [1]:
import numpy as np
from sklearn import preprocessing

In [2]:
X = np.array([[ 1., -1.,  2.],
              [ 2.,  0.,  0.],
              [ 0.,  1., -1.]])

In [3]:
# preprocessing.scale(X) makes mean to be 0 and variance to be 1
X_scaled = preprocessing.scale(X)
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [4]:
#making mean to be 0
X_scaled.mean(axis = 0)

array([0., 0., 0.])

In [5]:
#making standered deviation to be 1
X_scaled.std(axis= 0)

array([1., 1., 1.])

In [6]:
#same as scale function, its give an obj here as scaler then fit the scaler with 
# traning data(X) i.e scaler.fit(X), it finds the paramete using which it scale 
scaler = preprocessing.StandardScaler()
scaler.fit(X)
# then transform any data we want
scaler.transform(X)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [7]:
X_test = [[1,1,0]]
scaler.transform(X_test)

array([[ 0.        ,  1.22474487, -0.26726124]])