In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [30]:
df = pd.read_csv('BreastCancer_Prognostic_v12.csv')
df


ID Outcome   Time  radius_mean  texture_mean  perimeter_mean  \
0     119513.0       N   31.0        18.02         27.60          117.50   
1       8423.0       N   61.0        17.99         10.38          122.80   
2     842517.0       N  116.0        21.37         17.44          137.50   
3     843483.0       N  123.0        11.42         20.38           77.58   
4     843584.0       R   27.0        20.29         14.34          135.10   
5     843786.0       R   77.0        12.75         15.29           84.60   
6     844359.0       N   60.0        18.98         19.61          124.40   
7     844582.0       R   77.0        13.71         20.83           90.20   
8     844981.0       N  119.0        13.00         21.82           87.50   
9     845010.0       N   76.0        12.46         24.04           83.97   
10    845636.0       N  123.0        16.02         23.24          102.70   
11    846100.0       N  125.0        15.78         17.89          103.60   
12    846381.0       N  117.0        15.85         23.95          103.70   
13    847990.0       R   36.0        14.54         27.54           96.73   
14    848406.0       N  123.0        14.68         20.13           94.74   
15    848620.0       R   10.0        16.13         20.68          108.10   
16   8511133.0       N   20.0        15.34         14.26          102.50   
17    851509.0       R   10.0        21.16         23.04          137.20   
18    852552.0       N   96.0        16.65         21.38          110.00   
19    852631.0       N  116.0        17.14         16.40          116.00   
20    852763.0       N  103.0        14.58         21.53           97.41   
21    852781.0       N   16.0        18.61         20.25          122.10   
22    852973.0       N   52.0        15.30         25.27          102.40   
23    853201.0       N   94.0        17.57         15.05          115.00   
24    853612.0       N  116.0        11.84         18.70           77.93   
25    853826.0       N   87.0        17.02         23.98          112.80   
26    854002.0       N   53.0        19.27         26.47          127.90   
27    854039.0       N  109.0        16.13         17.88          107.00   
28    854253.0       N   12.0        16.74         21.59          110.10   
29    854268.0       N   31.0        14.25         21.72           93.63   
..         ...     ...    ...          ...           ...             ...   
168   925622.0       N   30.0        15.22         30.62          103.40   
169   926125.0       N   17.0        20.92         25.09          143.00   
170   926424.0       N   28.0        21.56         22.39          142.00   
171   926682.0       N   20.0        20.13         28.25          131.20   
172   926954.0       N   16.0        16.60         28.08          108.30   
173   927992.0       N   26.0        13.86         23.83           89.60   
174   927997.0       N   27.0        18.11         26.17          118.70   
175   928594.0       N   29.0        21.93         30.64          146.70   
176   929684.0       R   14.0        17.53         25.28          114.00   
177   931652.0       R    1.0        18.11         30.99          115.80   
178   931678.0       N   24.0        24.29         25.48          161.80   
179   935058.0       N   13.0        15.60         26.79           99.85   
180   935878.0       N   13.0        15.78         17.10          102.20   
181   937100.0       N   12.0        19.28         20.88          124.90   
182   937653.0       N   15.0        15.66         24.51          102.00   
183   937654.0       N   11.0        22.44         27.42          150.60   
184   937664.0       N   17.0        17.98         23.96          120.00   
185   937897.0       N   17.0        13.63         24.70           89.65   
186   938225.0       N    9.0        23.01         33.87          156.80   
187   938412.0       N   10.0        22.41         29.95          145.50   
188   938413.0       N   15.0        12.53         30.98    

In [31]:
df.shape

(198, 35)

In [32]:
from sklearn.model_selection import train_test_split
X = df.iloc[ : , 2:32 ].values
Y = df.iloc[ : , 1].values
l = LabelEncoder()
Y = l.fit_transform(Y)
print (X)
print(Y)

[[3.100e+01 1.802e+01 2.760e+01 ... 3.140e-01 1.170e-01 2.677e-01]
 [6.100e+01 1.799e+01 1.038e+01 ... 7.119e-01 2.654e-01 4.601e-01]
 [1.160e+02 2.137e+01 1.744e+01 ... 3.414e-01 2.032e-01 4.334e-01]
 ...
 [1.200e+01 1.717e+01 2.919e+01 ... 2.141e-01 9.520e-02 3.362e-01]
 [3.000e+00 2.142e+01 2.284e+01 ... 5.411e-01 2.215e-01 2.832e-01]
 [6.000e+00 1.670e+01 2.813e+01 ... 3.455e-01 1.317e-01 3.035e-01]]
[0 0 0 0 1 1 0 1 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 1 0 1 1 0 1 1 0 0 1 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 1 0 1 0 0 0 0
 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1
 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 1 0 1 0 1
 0 0 1 0 1 0 0 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0]


In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 42)

In [34]:
df.columns

Index(['ID', 'Outcome', 'Time', 'radius_mean', 'texture_mean',
       'perimeter_mean', 'area_mean', 'smoothness_mean', 'compactness_mean',
       'concavity_mean', 'concave_points_mean', 'symmetry_mean',
       'fractal_dimension_mean', 'radius_std_dev', 'texture_std_dev',
       'perimeter_std_dev', 'area_std_dev', 'smoothness_std_dev',
       'compactness_std_dev', 'concavity_std_dev', 'concave_points_std_dev',
       'symmetry_std_dev', 'fractal_dimension_std_dev', 'Worst_radius',
       'Worst_texture', 'Worst_perimeter', 'Worst_area', 'Worst_smoothness',
       'Worst_compactness', 'Worst_concavity', 'Worst_concave_points',
       'Worst_symmetry', 'Worst_fractal_dimension', 'Tumor_Size',
       'Lymph_Node_Status'],
      dtype='object')

In [35]:
from sklearn.preprocessing import StandardScaler

In [36]:
ss=StandardScaler()

In [37]:
X_train=ss.fit_transform(X_train)
X_test=ss.fit_transform(X_test)

In [38]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()

model1=lr.fit(X_train,y_train)
prediction1=model1.predict(X_test)

C:\Users\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [39]:
from sklearn.metrics import confusion_matrix

cm=confusion_matrix(y_test,prediction1)
cm

array([[30,  2],
       [ 3,  5]], dtype=int64)

In [40]:
from sklearn.metrics import accuracy_score

In [41]:
accuracy_score(y_test,prediction1)

0.875